import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';

// --- Helper Components ---

const StatCard = ({ icon, value, label }) => (
  <div className="stat-card">
    <i className={`fas ${icon}`}></i>
    <div className="stat-info">
      <span className="stat-value">{value}</span>
      <span className="stat-label">{label}</span>
    </div>
  </div>
);

const ActivityItem = ({ icon, title, subtitle, linkTo, onPreview, onDownload, isDocument }) => (
    <div className="activity-item-wrapper">
        <Link to={linkTo} className="activity-item">
            <div className="activity-icon">
                <i className={`fas ${icon}`}></i>
            </div>
            <div className="activity-details">
                <span className="activity-title">{title}</span>
                <span className="activity-subtitle">{subtitle}</span>
            </div>
            <i className="fas fa-arrow-right chevron"></i>
        </Link>
        {isDocument && (
            <div className="activity-actions">
                <button onClick={onPreview} className="btn btn-secondary dark btn-sm">Preview</button>
                <button onClick={onDownload} className="btn btn-primary btn-sm"><i className="fas fa-download"></i> Download</button>
            </div>
        )}
    </div>
);


// --- Main Activity Page Component ---

const ActivityPage = () => {
  const [documents, setDocuments] = useState([]);
  const [chats, setChats] = useState([]);
  const [showPreviewModal, setShowPreviewModal] = useState(false);
  const [previewContent, setPreviewContent] = useState({ title: '', content: '' });

  useEffect(() => {
    // Load jspdf script for PDF downloads
    const script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
    script.async = true;
    document.body.appendChild(script);

    const savedDocs = JSON.parse(localStorage.getItem('lawdekho_documents') || '[]');
    const savedChats = JSON.parse(localStorage.getItem('lawdekho_chat_history') || '[]');
    
    setDocuments(savedDocs.slice(-3).reverse());
    setChats(savedChats.filter(c => c.sender === 'user').slice(-3).reverse());
  }, []);

  const handlePreview = (doc) => {
    setPreviewContent({
        title: doc.title,
        content: doc.content
    });
    setShowPreviewModal(true);
  };

  const handleDownload = (doc) => {
    if (!window.jspdf) {
        alert("PDF library not loaded yet.");
        return;
    }
    const { jsPDF } = window.jspdf;
    const pdf = new jsPDF();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const pageWidth = pdf.internal.pageSize.getWidth();

    // Letterhead
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(20);
    pdf.setTextColor(41, 121, 255);
    pdf.text("Lawdekho", 15, 20);
    pdf.setDrawColor(229, 231, 235);
    pdf.line(15, 25, pageWidth - 15, 25);

    // Title
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(14);
    pdf.setTextColor(52, 58, 64);
    pdf.text(doc.title.toUpperCase(), pageWidth / 2, 40, { align: 'center' });

    // Actual content
    pdf.setFont("times", "normal");
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    const splitText = pdf.splitTextToSize(doc.content, 180);
    pdf.text(splitText, 15, 55);

    // Footer
    const footerY = pageHeight - 20;
    pdf.setDrawColor(229, 231, 235);
    pdf.line(15, footerY - 5, pageWidth - 15, footerY - 5);
    pdf.setFont("helvetica", "italic");
    pdf.setFontSize(8);
    pdf.setTextColor(108, 117, 125);
    pdf.text("Generated by Lawdekho (lawdekhoo.com)", pageWidth / 2, footerY, { align: 'center' });

    pdf.save(`${doc.title.replace(/ /g, '_')}.pdf`);
  };


  return (
    <div className="dashboard-page">
      <header className="dashboard-header">
        <div>
          <h2>Your Recent Activity</h2>
          <p>Find your recently generated documents and conversations with the AI assistant.</p>
        </div>
        <div className="header-actions">
          <Link to="/chat" className="btn btn-primary"><i className="fas fa-comment-dots"></i> Start AI Chat</Link>
          <Link to="/documents" className="btn btn-secondary dark"><i className="fas fa-file-alt"></i> Generate Document</Link>
        </div>
      </header>

      <div className="stats-grid">
        <StatCard icon="fa-comments" value={chats.length} label="Recent Chats" />
        <StatCard icon="fa-file-alt" value={documents.length} label="Recent Documents" />
      </div>

      <div className="recent-activity-grid">
        <div className="card">
          <div className="card-header">
            <h4>Recent Documents</h4>
            <Link to="/documents">View All</Link>
          </div>
          {documents.length > 0 ? (
            <div className="activity-list">
                {documents.map(doc => (
                    <ActivityItem 
                        key={doc.id} 
                        icon="fa-file-alt" 
                        title={doc.title} 
                        subtitle={`Generated on ${doc.date}`} 
                        linkTo="/documents"
                        isDocument={true}
                        onPreview={() => handlePreview(doc)}
                        onDownload={() => handleDownload(doc)}
                    />
                ))}
            </div>
          ) : (
            <div className="empty-state">
              <p>No documents generated yet.</p>
              <Link to="/documents" className="btn btn-primary">Generate Your First Document</Link>
            </div>
          )}
        </div>
        <div className="card">
          <div className="card-header">
            <h4>Recent Chats</h4>
            <Link to="/chat">View All</Link>
          </div>
          {chats.length > 0 ? (
             <div className="activity-list">
                {chats.map(chat => (
                    <ActivityItem 
                        key={chat.id} 
                        icon="fa-comment-dots" 
                        title={`"${chat.text.substring(0, 40)}..."`} 
                        subtitle="From AI Chat" 
                        linkTo="/chat" 
                    />
                ))}
             </div>
          ) : (
            <div className="empty-state">
                <p>No chats started yet.</p>
                <Link to="/chat" className="btn btn-primary">Start a Chat</Link>
            </div>
          )}
        </div>
      </div>

      {showPreviewModal && (
        <div className="modal-overlay" onClick={() => setShowPreviewModal(false)}>
          <div className="modal-content card" onClick={(e) => e.stopPropagation()}>
            <h3>{previewContent.title}</h3>
            <div className="preview-content-area">
                <textarea readOnly value={previewContent.content} />
            </div>
            <div className="modal-actions">
              <button type="button" className="btn btn-secondary dark" onClick={() => setShowPreviewModal(false)}>Close</button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default ActivityPage;
